name: $(Build.DefinitionName)_$(Build.SourceBranchName)_1.0.0.$(rev:rrr)

trigger:
  batch: true
  branches:
    include:
    - main

variables:
  - group: 'Pipelines Global'
  - name: DDTIGeneratorSolution
    value: 'DDTIGenerator\Sources\DDTIGenerator.sln'
  - template: /Deployment/Pipelines/Variables/variables-si14.yml@SI

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Test
    displayName: 'Test Extensions'
    steps:

    - checkout: self
      lfs: true
    
    - task: HelloWorld@2
      inputs:
        name: 'Abhishek'
    
    - task: PromoteToView@1
      inputs:
        feedName: 'TestPromote'
        feedScoped: 'Organization'
        view: 'Prerelease'
        nugetPackageMappingFilePath: '$(build.sourcesdirectory)\Inputs to Extensions\NugetPackageMapping.psd1'