name: $(Build.DefinitionName)_$(Build.SourceBranchName)_1.0.0.$(rev:rrr)

trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  - group: 'Extension Pipeline Global'

jobs:
  - job: Test
    displayName: 'Test Extensions'
    steps:

    - checkout: self
      lfs: true

    - task: HelloWorld@2
      displayName: HelloWorld-Extension
      inputs:
        name: 'Abhishek'
    
    - task: PromoteToView@1
      displayName: PromoteToView-Extension
      inputs:
        feedName: 'TestPromote'
        feedScoped: 'Organization'
        view: 'Release'
        nugetPackageMappingFilePath: '$(build.sourcesdirectory)/Inputs to Extensions/NugetPackageMapping.psd1'
      env:
        SYSTEM_ACCESSTOKEN: $(SYSTEM_ACCESSTOKEN)
        devAzureOrganizationUrl: $(devAzureOrganizationUrl)