name: 1.0.0.$(rev:rrr)

trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: 'windows-latest'

variables:
  - group: 'Extension Pipeline Global'
  - name: InputsToExtension
    value: $(build.sourcesdirectory)/Inputs to Extensions

jobs:
  - job: Test
    displayName: 'Extensions Test'
    steps:

    - checkout: self
      lfs: true

    - task: HelloWorld@1
      displayName: HelloWorld-Extension
      inputs:
        name: 'Abhishek'

    - task: PromoteToView@2
      displayName: PromoteToView-Extension
      inputs:
        feedName: 'TestPromote'
        feedScoped: 'Organization'
        view: 'Release'
        nugetPackageMappingFilePath: '$(InputsToExtension)/NugetPackageMapping.psd1'
      env:
        SYSTEM_ACCESSTOKEN: $(SYSTEM_ACCESSTOKEN)
        devAzureOrganizationUrl: $(devAzureOrganizationUrl)
    
    - task: ApplyVersion@1
      inputs:
        SourceFolder: '$(InputsToExtension)/ApplyVersion'
        Product: 'CodeBuildOps ApplyVersion'
        Copyright: '2025'
        Company: 'CodeBuildOps'